export enum Icons {
	card = '/icons/card.svg',
	cardPay = '/icons/cardPay.svg',
	payment = '/icons/payment.svg',
	faq = '/icons/faq.svg',
	support = '/icons/support.svg',
	terms = '/icons/terms.svg',
	security = '/icons/terms.svg',
	defaultAvatar = '/icons/user.svg',
	logout = '/icons/logout.svg',
	profile = '/icons/profile.svg',
	arrowDown = '/icons/arrow-bottom.svg',
	notification = '/icons/notification.svg',
	locked = '/icons/locked.svg',
	user = '/icons/user.svg',
	hidePassword = '/icons/hidePassword.svg',
	showPassword = '/icons/showPassword.svg',
	exclamation = '/icons/exclamation.svg',
	arrowUpBlue = '/icons/arrow-up-blue.svg',
	arrowDownRed = '/icons/arrow-down-red.svg',
	arrowSolidLeft = '/icons/arrow-solid-left.svg',
	iconTrash = '/icons/delete.svg',
	iconTrashPure = '/icons/trash-pure.svg',
}
