export enum PermissionsEnums {
  VIEW = "view",
  EDIT = "edit",
  ADD = "add",
  DETAIL = "detail",
  DAR_DE_BAJA_MIEMBRO = "DAR_DE_BAJA_MIEMBRO",
  DETALLE_MIEMBRO = "DETALLE_MIEMBRO",
  LOAD_FORMS = "LOAD_FORMS",
  VIEW_DATA_FORMS = "VIEW_DATA_FORMS",
  APPROVE_FORM = "APPROVE_FORM",
  LOAD_SCORE = "LOAD_SCORE",
}
