export enum UseQueryEnums {
  GET_PRESIDENTES_CONSEJO = "GET_PRESIDENTES_CONSEJO",
  GET_ALL_CONSEJOS_REGIONALES = "GET_ALL_CONSEJOS_REGIONALES",
  GET_ALL_DISTRITOS = "GET_ALL_DISTRITOS",
  GET_ALL_IGLESIAS = "GET_ALL_IGLESIAS",
}
